# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170406_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoitem',
            name='gasto',
        ),
        migrations.RemoveField(
            model_name='gastoitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='item',
        ),
        migrations.AddField(
            model_name='gasto',
            name='items',
            field=models.ManyToManyField(to='app.Item'),
        ),
        migrations.DeleteModel(
            name='GastoItem',
        ),
    ]
