# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_gasto_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
