# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170408_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='valor',
        ),
        migrations.AddField(
            model_name='item',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
