# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gasto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='items',
        ),
        migrations.AddField(
            model_name='gasto',
            name='items',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
            preserve_default=False,
        ),
    ]
