# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170408_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(),
        ),
    ]
