# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='gasto',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
