# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170408_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_user',
            field=models.ManyToManyField(to='app.User'),
        ),
    ]
