# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id_user',
        ),
        migrations.AddField(
            model_name='item',
            name='id_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.User'),
            preserve_default=False,
        ),
    ]
