# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170409_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id_user',
        ),
        migrations.AddField(
            model_name='item',
            name='d_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
