# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170409_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='d_user',
            new_name='id_user',
        ),
    ]
