# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170409_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='descricao',
        ),
        migrations.AddField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
