# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170410_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(default=''),
        ),
    ]
