# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170410_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
